### ISSUE TITLE
'BetterWorldQuests' tried to call the protected function 'Frame:SetPropagateMouseClicks()'.

### ISSUE THREAD

**Issue by Treacherouz** [p3lim-wow/BetterWorldQuests#69] opened 2024-10-15 14:55 UTC
5x [ADDON_ACTION_BLOCKED] AddOn 'BetterWorldQuests' tried to call the protected function 'Frame:SetPropagateMouseClicks()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPropagateMouseClicks'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:459: in function `UpdateMousePropagation'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:464: in function `OnAcquired'
[string "@Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua"]:555: in function `OnAcquired'
[string "@Blizzard_SharedMapDataProviders/AreaPOIDataProvider.lua"]:111: in function <...zzard_SharedMapDataProviders/AreaPOIDataProvider.lua:110>
[string "=[C]"]: in function `OnAcquired'
[string "@Blizzard_SharedMapDataProviders/StorylineQuestDataProvider.lua"]:474: in function `OnAcquired'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:204: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/StorylineQuestDataProvider.lua"]:299: in function `CheckAddHubPins'
[string "@Blizzard_SharedMapDataProviders/StorylineQuestDataProvider.lua"]:319: in function `RefreshAllData'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:476: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:475>
...
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:880: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:866>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:106: in function `SetDisplayState'
[string "@Blizzard_WorldMap/QuestLogOwnerMixin.lua"]:42: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:511: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:510>
[string "=[C]"]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**How to reproduce**
Unknown

**Comment by p3lim** [comment] 2024-10-15 15:40
Duplicate of #53

**Closed by p3lim** 2024-10-15 15:40 UTC
Labels: bug
