### ISSUE TITLE
WoW Interface issue

### ISSUE THREAD

**Issue by Mallust1** [p3lim-wow/BetterWorldQuests#54] opened 2024-08-25 12:59 UTC
**Describe the bug**
When questing and you get a quest that has item to click next to it WoW popup box comes up saying BetterWorldQuest has been blocked untl you reload ui. Then it lets you use the item. Doesnt always happen but usually on trying to use item first try.

**How to reproduce**
PIck up quest that you have item to click next to the quest.

**What did you expect?**
Just expect to be able to use the item in quest log without a error message popping up that you cant use that item do to WoW Interface blocking Better World Quest from doing that. 

**Screenshots**

**Comment by p3lim** [comment] 2024-08-25 13:09
Duplicate of #53.

**Closed by p3lim** 2024-08-25 13:09 UTC
Labels: bug
