### ISSUE TITLE
'BetterWorldQuests' tried to call the protected function 'Frame:SetPassThroughButtons()'.

### ISSUE THREAD

**Issue by Treacherouz** [p3lim-wow/BetterWorldQuests#70] opened 2024-10-15 14:56 UTC
1x [ADDON_ACTION_BLOCKED] AddOn 'BetterWorldQuests' tried to call the protected function 'Frame:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua"]:167: in function `PingQuestID'
[string "@Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua"]:84: in function <...rd_SharedMapDataProviders/WorldQuestDataProvider.lua:83>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:501: in function `PingQuestID'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:1072: in function `QuestMapFrame_PingQuestID'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:993: in function <...ns/Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua:992>
[string "=[C]"]: in function `QuestMapFrame_ShowQuestDetails'
[string "@Blizzard_UIPanels_Game/Mainline/QuestMapFrame.lua"]:1121: in function `QuestMapFrame_OpenToQuestDetails'
[string "@Blizzard_ObjectiveTracker/Blizzard_QuestObjectiveTracker.lua"]:65: in function <..._ObjectiveTracker/Blizzard_QuestObjectiveTracker.lua:50>
[string "=[C]"]: in function `OnBlockHeaderClick'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerBlock.lua"]:285: in function `OnHeaderClick'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerBlock.lua"]:377: in function <..._ObjectiveTracker/Blizzard_ObjectiveTrackerBlock.lua:375>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**How to reproduce**
Clicking the quest tracker item button. This in turn throws an error stating that Better World Quests is blocking the use of the quest tracker item button.

**What did you expect?**
Being able to use the quest tracker item button.

**Comment by p3lim** [comment] 2024-10-15 15:40
Duplicate of #53

**Closed by p3lim** 2024-10-15 15:40 UTC
Labels: bug
